// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CitizenDBContext))]
    [Migration("20260112131453_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregate.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Domain.Aggregate.CitizenArea", b =>
                {
                    b.Property<Guid>("CitizenAreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CitizenAreaID");

                    b.ToTable("CitizenAreas");
                });

            modelBuilder.Entity("Domain.Aggregate.CitizenProfile", b =>
                {
                    b.Property<Guid>("CitizenProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointBalance")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CitizenProfileID");

                    b.ToTable("CitizenProfiles");
                });

            modelBuilder.Entity("Domain.Entity.CollectionReport", b =>
                {
                    b.Property<Guid>("CollectionReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollectionReportID");

                    b.HasIndex("CitizenProfileID");

                    b.ToTable("CollectionReports");
                });

            modelBuilder.Entity("Domain.Entity.ComplaintReport", b =>
                {
                    b.Property<Guid>("ComplaintReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenAreaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplaintReportID");

                    b.HasIndex("CitizenAreaID");

                    b.HasIndex("CitizenProfileID");

                    b.ToTable("ComplaintReports");
                });

            modelBuilder.Entity("Domain.Entity.RewardHistory", b =>
                {
                    b.Property<Guid>("RewardHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenAreaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RewardHistoryID");

                    b.HasIndex("CitizenAreaID");

                    b.HasIndex("CitizenProfileID");

                    b.ToTable("RewardHistories");
                });

            modelBuilder.Entity("Domain.Entity.CollectionReport", b =>
                {
                    b.HasOne("Domain.Aggregate.CitizenProfile", null)
                        .WithMany("CollectionReports")
                        .HasForeignKey("CitizenProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObject.GPS", "GPS", b1 =>
                        {
                            b1.Property<Guid>("CollectionReportID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("CollectionReportID");

                            b1.ToTable("CollectionReports");

                            b1.WithOwner()
                                .HasForeignKey("CollectionReportID");
                        });

                    b.Navigation("GPS")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.ComplaintReport", b =>
                {
                    b.HasOne("Domain.Aggregate.CitizenArea", "CitizenArea")
                        .WithMany()
                        .HasForeignKey("CitizenAreaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregate.CitizenProfile", null)
                        .WithMany("ComplaintReports")
                        .HasForeignKey("CitizenProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenArea");
                });

            modelBuilder.Entity("Domain.Entity.RewardHistory", b =>
                {
                    b.HasOne("Domain.Aggregate.CitizenArea", "CitizenArea")
                        .WithMany()
                        .HasForeignKey("CitizenAreaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregate.CitizenProfile", null)
                        .WithMany("RewardHistories")
                        .HasForeignKey("CitizenProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitizenArea");
                });

            modelBuilder.Entity("Domain.Aggregate.CitizenProfile", b =>
                {
                    b.Navigation("CollectionReports");

                    b.Navigation("ComplaintReports");

                    b.Navigation("RewardHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
